---
title: "Age Is Just A Number…Statistically Speaking"
author: "Jason Jones"
date: 2018-11-12T21:09:00-00:00
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```


```{r}
library(tidyverse)
library(lubridate)
```


```{r}
bulk_dat <- read_csv("https://www.dallasopendata.com/api/views/ftja-9jxd/rows.csv",
                     col_types = cols(offensereportingofficerbadge2 = col_character(),
                                      offensebeat = col_character())) %>%
  mutate(offensedate = as.Date(offensedate, format = "%m/%d/%Y"))
```



```{r}
bulk_dat <- bulk_dat %>%
  mutate(hour = hour(offensetimeofoccurence2)) %>%
  mutate(age = as.integer(offenseage)) %>%
  mutate(month = month(offensedate))
```



```{r}
bulk_dat %>%
  ggplot(aes(age)) +
  geom_histogram(aes(y = ..density..),
                 binwidth = 5, color = "black", fill = "white") +
  geom_density(alpha = .2, fill = "blue") +
  geom_vline(aes(xintercept = mean(age, na.rm = TRUE)), color = "red", linetype = "dashed", size = 1)
```


```{r}
bulk_dat %>%
  ggplot(aes(hour)) +
  geom_histogram(aes(y = ..density..),
                 binwidth = 2, color = "black", fill = "white") +
  geom_density(alpha = .2, fill = "blue") +
  geom_vline(aes(xintercept = mean(hour, na.rm = TRUE)), color = "red", linetype = "dashed", size = 1)
```



```{r}
bulk_dat %>%
  ggplot(aes(month)) +
  geom_histogram(aes(y = ..density..),
                 binwidth = 1, color = "black", fill = "white") +
  geom_density(alpha = .2, fill = "blue") +
  geom_vline(aes(xintercept = mean(month, na.rm = TRUE)), color = "red", linetype = "dashed", size = 1)
```

